version: "3.7"
services:
  servicemysql:
    container_name: mysql-expediente
    image: mysql
    ports:
      - 3003:3306
    volumes:
      - volume-mysql-expediente:/var/lib/mysql
    networks:
      sistema-expediente-notas:
        ipv4_address: 192.168.9.3
    environment:
      MYSQL_ROOT_PASSWORD: root


  servicephpmyadmin:
    container_name: phpmyadmin-expediente
    image: phpmyadmin
    ports:
      - 8085:80
    networks:
      sistema-expediente-notas:
        ipv4_address: 192.168.9.4
    environment:
      PMA_HOST: 192.168.9.3
      PMA_PORT: 3306



volumes:
  volume-mysql-expediente:
  volume-phpmyadmin-expediente:
  

networks:
  sistema-expediente-notas:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.9.0/24
          gateway: 192.168.9.1

